### ISSUE TITLE
Libsentry.so is not resolvable warning

### ISSUE THREAD

**Issue by Edstub207** [getsentry/sentry-unreal#188]
### Environment
Unreal 

How do you use Sentry?
Sentry SaaS (sentry.io)

Which version of the SDK?
Latest from Main 

How did you install the package? (Git-URL, Assetstore)
Manually

Which version of Unreal?
5.1

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
Compiling the server for Linux 

### Steps to Reproduce
1. Compile the server for a project Linux against the Linux platform on a Windows Build agent with warnings as errors and strict compile enabled 

### Expected Result
No warnings or errors

### Actual Result
Library 'E:\Horde\Work\Sync\Project\Plugins\External\SentryUnrealPlugin\Binaries\Linux\libsentry.so' was not resolvable to a file when used in Module 'Sentry', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.

**Comment by tustanivsky** [comment]
This issue was addressed in the scope of #190

**Comment by tustanivsky** [comment]
Just a quick update regarding this warning - in order to fix it I had to put back the code for copying plugin dependencies to `Binaries` folder before calling the `PublicAdditionalLibraries.Add("...\libsentry.so")` method in `Sentry.Build.cs`. The thing is that even though the `RuntimeDependencies.Add(dst, src)` copies the binaries on its own it happens at some later build stages and by the time of "adding" `libsentry.so` they aren't there yet. Linking [this](https://github.com/getsentry/sentry-unreal/commit/dc7db942868dae260200657f6b718d2f40ed22a9#commitcomment-94273387) conversation for extra context
