### ISSUE TITLE
Crash reporter is not showing up anymore after adding the sentry plugin to the project

### ISSUE THREAD

**Issue by Shuusui** [getsentry/sentry-unreal#404]
### Environment

How do you use Sentry?
I'm currently in the setup process of sentry.io to see if everything works.

Which version of the SDK?
I'm using the 0.11.0 version from here https://github.com/getsentry/sentry-unreal/releases

Which version of Unreal?
5.2, source build

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
Anywhere

### Steps to Reproduce

1. Installing the plugin
2. Build game or however it should get tested
3. open console and type debug crash 
4. Game crashes, report gets send, crash reporter client is not showing

I also tried to set it up like mentioned on this page https://docs.sentry.io/platforms/unreal/configuration/setup-crashreporter/ without any changes.

**Comment by tustanivsky** [comment]
Hey there @Shuusui, I think the reason why `Crash Reporter Client` doesn't show up anymore is the checked `Enable automatic crash capturing (Windows, UE 5.2+)` option in the `Project Settings -> Plugins -> Sentry` menu.

Basically, Sentry plugin supports two types of crash capturing - the first relies on Unreal's CRC which acts as a proxy for uploading reports to Sentry while the second one utilizes `sentry-native` library that's integrated into the plugin and is enabled by default starting from UE 5.2. Thing is that you can not use both simultaneously since these mechanisms are mutually exclusive. If you prefer to keep using CRC along with Sentry plugin just uncheck the above option and that should do the trick.

**Comment by Shuusui** [comment]
Hey @tustanivsky, that was it. Thanks for your quick answer. 
It would be nice if this would be a bit more clear from the documentation because I read the documentation several times yesterday and wasn't sure what's wrong. 
Glad that it works now anyway. It's also a very neat feature that we don't need the crash reporter and everything works out of the box from now ongoing

**Comment by tustanivsky** [comment]
Thanks for the heads-up! Actually, the documentation update is currently in progress so I'll make sure that this topic is covered there as well.

Closing it now since the original issue seems to be resolved however feel free to raise another one if anything else comes up.
