### ISSUE TITLE
Android SDK integration doesn't use locally build package

### ISSUE THREAD

**Issue by tustanivsky** [getsentry/sentry-unreal#42]
Crashes captured on Android should provide info regarding the native SDK name which is used under the hood by the UE plugin (`sentry.native.android.unreal`), however default value is used instead.

#26 

SDK name for sentry-java is specified in a corresponding build script: https://github.com/getsentry/sentry-unreal/blob/main/Scripts/build-java.sh

**Comment by vaind** [comment]
The cause is that we're not actually using the built `.aar`s but using a standard android dependency from mavencentral. This is what ends up in the project:

```groovy
repositories {
	maven { url uri('C:/Program Files/Epic Games/UE_4.27/Engine/Source/ThirdParty/Android/extras/google/m2repository') }
	maven { url uri('C:/Program Files/Epic Games/UE_4.27/Engine/Source/ThirdParty/Android/extras/android/m2repository') }
	maven { url uri('C:/dev/sentry-unreal/sample/Plugins/sentry/Source/ThirdParty/Android') }
}
dependencies {
	implementation 'com.google.android.gms:play-services-auth:11.8.0'
	implementation 'com.google.android.gms:play-services-games:11.8.0'
	implementation 'com.google.android.gms:play-services-nearby:11.8.0'
	implementation 'com.google.android.gms:play-services-plus:11.8.0'
	implementation 'io.sentry:sentry:6.3.1'
	implementation 'io.sentry:sentry-android-core:6.3.1'
	implementation 'io.sentry:sentry-android-ndk:6.3.1'
}
```

* the `Plugins/sentry/Source/ThirdParty/Android` isn't a maven-structured local repo
* I've tried deleting the local android build and the deps are still resolved and the app launches

----

Using actual dependency from mavenCentral has it's pros, like we don't have to build & package. Do we want to do that?
