### ISSUE TITLE
Is automatic exception catching and reporting functionnal ?

### ISSUE THREAD

**Issue by SBRK** [getsentry/sentry-unreal#44]
### Environment

Sentry SaaS (sentry.io) 
Plugin 0.0.1
Unreal 5.0.3
Windows 10

### Steps to Reproduce

1. Configure Sentry plugin and Sentry project
2. Capture a custom "Hello World" message => works ok and is visible in Sentry issues panel
3. Trigger an exception in Unreal

### Expected Result
Error gets reported in Sentry issues

### Actual Result
Nothing gets sent

The documentation of the plugin insinuate that it should automatically send crashes. It doesn't seem to be the case. Is there anything special to do to make it work ? Is it simply not supported yet ?

**Comment by tustanivsky** [comment]
Hey @SBRK , in order to capture crashes on Windows please [configure Crash Reporter](https://docs.sentry.io/platforms/unreal/setup-crashreport/) first.
This step won't be required once the next engine version goes live, however for now UE has some limitations in terms of exception handling on desktop.

**Comment by SBRK** [comment]
[Crash Reporter seems to be broken for me at the moment](https://github.com/getsentry/sentry/issues/37106) so I was looking at this new plugin as an alternative

**Comment by tustanivsky** [comment]
@Edstub207 
1. For Sentry plugin configuration (`ProjectSettings` -> `Plugins` -> `Sentry`) you should use the DSN. However, for the embedded Crash Reporter UE specific version has to be provided as it is described [here](https://docs.sentry.io/platforms/unreal/setup-crashreport/#configure-the-crash-reporter-endpoint)
2. No, currently there is no support for that

**Comment by bruno-garcia** [comment]
We heard this will be soon possible in some 5.1 or future version of Unreal.

**Comment by vaind** [comment]
I can't find any info on when is 5.1 expected to be released, though.

In any case, this looks to me like a documentation issue at this time - we should clearly indicate in the Configure section https://docs.sentry.io/platforms/unreal/#configure that there is another step that should be taken.

**Comment by Edstub207** [comment]
@vaind Epic have branched for 5.1 already, so it should be in the next few weeks/months.

**Comment by tustanivsky** [comment]
In UE 5.1 Epic Games introduced a new API allowing to disable the default crash handler and use a 3rd party one instead (https://github.com/EpicGames/UnrealEngine/pull/7976). However not all the changes suggested in this PR end up in the engine's `main` branch and therefore this functionality doesn't work as expected. I've created another PR to UE (https://github.com/EpicGames/UnrealEngine/pull/9931) which is supposed to address this issue. For now automatic crash capturing will work only in an editor (Windows, UE 5.1). Alternatively, corresponding changes can be applied to the engine's source code in order to make the Sentry plugin work in packaged game builds.

**Comment by tustanivsky** [comment]
Now with UE 5.2 it's finally possible to capture crashes automatically on Windows by checking the `EnableAutoCrashCapturing` option in Sentry plugin's settings menu. This also means that configuring Crash Reporter is not a required step anymore.
