### ISSUE TITLE
Latest Sentry github release doesn't work in Mac

### ISSUE THREAD

**Issue by mghimirewhitehat** [getsentry/sentry-unreal#476]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which version of the SDK?
0.15.1

How did you install the package? (Git-URL, Assetstore)
Git

Which version of Unreal?
5.2.1

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
Mac

### Steps to Reproduce

1. Downloaded github package from release page https://github.com/getsentry/sentry-unreal/releases for unreal 5.2
2. Created folder Plugins/Sentry inside the Unreal project
3. When i opened the unreal project it is saying that  "sentry.dylib" cannot be opened because the developer cannot be verified.

### Expected Result

Sentry should run smoothly as expected.

### Actual Result

Sentry is not initialized.

**Comment by tustanivsky** [comment]
@mghimirewhitehat Apparently this issue occur due to some system security settings on your Mac. To run the UE project with Sentry plugin installed please try the following:

1. Open `System Settings`
2. Click `Privacy & Security`, scroll down to the `Security` section and leave this window open for now
3. Run the UE project once again
4. After the popup with aforementioned warning regarding `sentry.dylib` appears click `Cancel` and return to the system settings window
5. Now you should see the `Allow Anyway` button there, click it to proceed (password/touchID input could be required to confirm the operation)
6. Click `Cancel` in warning popup once again
7. Click `Open` in another warning popup that appears right after
8. Unreal Editor should be opened and ready to use Sentry plugin

Please let us know whether it helped.

<img width="924" alt="image" src="https://github.com/getsentry/sentry-unreal/assets/3168564/4eacdf24-2b32-4a65-9339-c18df473c555">

**Comment by mghimirewhitehat** [comment]
Hi @tustanivsky ,

Thank you for your response, this approach works in editor. However when i package the game and codesign with my Developer ID Application certificate it is throwing Developer is not verified pop up in my other Mac, before sentry, it was successfully installed without any issue.

**Comment by tustanivsky** [comment]
While this requires additional investigation on our side here are a few other workarounds that could help:

1. Sentry plugin is available at UE Marketplace so downloading it via the Epic Games launcher instead of using the GitHub package might be something that will allow avoiding the above issues.
2. You can try to clone this repo and do the required setup manually by running `./scripts/init.sh` script which downloads the plugin's dependencies. Once it's done `plugin-dev` directory should contain a ready-to-use package. Note that you'll need GitHub CLI to be installed on your development machine.
3. Same as `2` but instead of downloading pre-built plugin dependencies you can build them locally by running the `./scripts/build-deps.ps1` script. It could be a bit tricky though since the additional dev environment setup could be required.

**Comment by tustanivsky** [comment]
> I have also downloaded from UE Marketplace but that wasn't uploading necessary debug files to the sentry since my project is C++ & blueprint one.

On Mac the only difference between GitHub and Marketplace packages is that in case with the second one you'll have to download `Sentry CLI` (debug symbol uploading tool) manually via the plugin's settings menu. Other than that the plugin behavior should be the same

**Comment by mghimirewhitehat** [comment]
In the Debug Symbols i have configured the details, and have also downloaded sentry-cli using npm install -g @sengtry/cli.
However the files are not uploaded while packaging the game.

![image](https://github.com/getsentry/sentry-unreal/assets/110440467/4d5754b8-86d9-4451-af71-bf661e976ced)

**Comment by tustanivsky** [comment]
I'll double-check the debug symbols uploading, yet it seems to be unrelated to the original issue. It would be great though if you could confirm whether the problem with `sentry.dylib` persists for the UE Marketplace plugin version on Mac.

**Comment by mghimirewhitehat** [comment]
After downloading from UE Marketplace, the problem with sentry.dylib is fixed on Mac however issue with debug symbols uploading still exists.
