### ISSUE TITLE
should i gitignore .sentry-native?

### ISSUE THREAD

**Issue by chiptus** [getsentry/sentry-unreal#614]
I recently added the sentry plugin to my game, and seeing that `.sentry-native` kept changing, I added to gitignore.

Users have complained on different issues related to it. should I return it to the repo?

will it keep changing?

**Comment by tustanivsky** [comment]
@chiptus You don't need to keep the `.sentry-native` folder under source control since it just stores the temporary data that is required by Sentry.

Can you elaborate on those issues your users are facing?

**Comment by chiptus** [comment]
@tustanivsky thanks for replying

they get the following message:

![Image](https://github.com/user-attachments/assets/a1882346-8be2-497f-8884-01c574fe120f)

basically it says this file is missing

**Comment by chiptus** [comment]
players keep getting these messages, so we've decided to remove sentry until we clear these

**Comment by tustanivsky** [comment]
@chiptus I'm sorry to hear that you've had this issue. 

Is there any chance that `.sentry-native` temporary folder was distributed to your Steam users along with the other game assets? Sentry regenerates everything within it on every game launch so the validation process could fail if it still expects its original content to be there.

As mentioned above `.sentry-native` should be gitignored and not be included in the game's final package.

**Comment by chiptus** [comment]
First, you should write that in your unreal sentrt guide.
Second, i understood that and gitignored it from the beginning, but our
users still saw it

**Comment by tustanivsky** [comment]
@chiptus After investigating it a bit more I think the possible workaround for this issue is to change the location of `.sentry-native` folder which Sentry creates upon the first game launch here:

https://github.com/getsentry/sentry-unreal/blob/b2d54675f88088f80d6c55b1fe2c8c925775ff1a/plugin-dev/Source/Sentry/Private/Desktop/SentrySubsystemDesktop.cpp#L527

Replacing `FPaths::ProjectDir()` with `FPaths::ProjectUserDir()` should technically allow avoiding any potential overhead by saving temporary files in the game install directory (like "Program Files" on Windows) which could be write-protected. Instead, these will be placed in the OS-specific user folder (i.e. "C:/Users/<username>/AppData/Local/<project_name>") and not interfere with the Steam files validation process.

It's important to make sure that `.sentry-native` folder is not only gitignored but removed from the source control entirely and that its content doesn't end up in the resulting game package which is then distributed to users.

**Comment by chiptus** [comment]
Sounds like a great fix, when will this go into an update?

**Comment by tustanivsky** [comment]
> Sounds like a great fix, when will this go into an update?

The PR #616 is already there so the potential fix will be included in the next release (probably right after it's merged).

**Comment by chiptus** [comment]
thank you, looking forward to it
