### ISSUE TITLE
Distributed tracing: Fixing clock skew

### ISSUE THREAD

**Issue by Acren** [getsentry/sentry-unreal#714]
Hello,

We are using the new distributed tracing in the UE SDK with our other services running Sentry.
This is working well other than the clock skew.

The documentation notes:
> [Clock Skew](https://docs.sentry.io/concepts/key-terms/tracing/distributed-tracing/#clock-skew)
> Collecting transactions from multiple machines may result in clock skew, where timestamps in one transaction don't align with timestamps in another. To reduce this, use Network Time Protocol (NTP) or your cloud provider's clock synchronization services.

So, following this, if we use an NTP server as suggested to calculate the corrected local time, how do we then use the corrected time with the Sentry SDK to fix the transaction and span timestamps?

Much thanks,
Sam

**Comment by tustanivsky** [comment]
The UE SDK doesn't currently provide an interface to override transaction and span timestamps. However, the underlying `sentry-native` library introduced APIs allowing to set custom timestamps in a recent update which might be worth exploring (see [PR #1093](https://github.com/getsentry/sentry-native/pull/1093) for details and [issue #941](https://github.com/getsentry/sentry-native/issues/941) for additional context).

Alternatively, you can try using lower-level calls to the native SDK to modify transaction/span objects directly like this:
```cpp
uint64_t correctedTimestamp = /* your corrected UNIX timestamp */;
sentry_value_set_by_key(transaction, "start_timestamp", 
    sentry__value_new_string_owned(sentry__usec_time_to_iso8601(correctedTimestamp)));
```

**Comment by Acren** [comment]
Thanks for the response. What's the correct way to call `sentry_value_set_by_key `via the UE SDK in this case? As far as I can see there doesn't seem to be a way to access the native transaction object from a `USentryTransaction `or `ISentryTransaction`, unless I'm mistaken.

**Comment by tustanivsky** [comment]
> However, the underlying sentry-native library introduced APIs allowing to set custom timestamps in a recent update which might be worth exploring (see https://github.com/getsentry/sentry-native/pull/1093 for details and https://github.com/getsentry/sentry-native/issues/941 for additional context).

@Acren I've opened a PR ([#715](https://github.com/getsentry/sentry-unreal/pull/715)) that adds these new APIs to Unreal plugin. Currently, their usage is limited to Windows and Linux so that's something to keep in mind if you're considering to support Apple/Android. You can give it a try by downloading the [updated package](https://github.com/getsentry/sentry-unreal/actions/runs/12370528731/artifacts/2331007921) from our GitHub CI.

> What's the correct way to call `sentry_value_set_by_key` via the UE SDK in this case?

You can't access native transaction objects directly. Instead, you'll need to add timestamp setter to `SentrySubsystemDesktop` and expose it via `ISentryTransaction`/`USentryTransaction` to ensure its value can be passed from Unreal to the native SDK layer. The linked PR might serve as a helpful reference for implementing this.

> Can this be done with SetData or SetTag?

No, Sentry backend treats tags and extra data differently so you won't be able to achieve the exact same result by using those.

**Comment by Acren** [comment]
Thanks a lot for that, I tried that version and it works perfectly.

**Comment by tustanivsky** [comment]
Awesome, thank you for confirming it works!
